//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirTechTechnicalTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HomeSearching
    {
        public int Id { get; set; }
        public int LocationId { get; set; }
        public string Office { get; set; }
        public Nullable<double> Area { get; set; }
        public Nullable<int> Bed { get; set; }
        public Nullable<int> Baths { get; set; }
        public Nullable<decimal> Price { get; set; }
    
        public virtual Location Location { get; set; }
    }
}
